### ISSUE TITLE
下载失败了，碎片文件怎么合并？

### ISSUE THREAD

**Issue by lweo** [Harlan-H/M3u8Downloader_H#13]
![image](https://user-images.githubusercontent.com/2786659/208296158-17a2b835-9f8f-4f0d-b093-df2c0d4e9ae2.png)
![image](https://user-images.githubusercontent.com/2786659/208296162-eadb926a-4ff6-4693-98e9-9d0f4004527f.png)

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at M3u8Downloader_H.Common.Extensions.HttpClientExtension.GetStreamAndUriAsync(HttpClient httpClient, Uri uri, IEnumerable`1 headers, CancellationToken cancellationToken)
   at M3u8Downloader_H.M3U8.M3UFileReaderManangers.M3UFileReaderManager.GetM3u8FileInfo(Uri uri, IEnumerable`1 headers, CancellationToken cancellationToken)
   at M3u8Downloader_H.M3U8.M3UFileReaderManangers.M3UFileReaderManager.GetM3u8FileInfo(Uri uri, IEnumerable`1 headers, Boolean isRetry, CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloadLiveSource.GetLiveFileInfos(Uri url, IEnumerable`1 Headers, CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloadLiveSource.GetM3U8FileInfoAsync(CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloadLiveSource.DownloadAsync(CancellationToken cancellationToken)
   at M3u8Downloader_H.Services.DownloadService.DownloadAsync(IDownloaderSource downloaderSource, DownloadRateSource downloadRate, CancellationToken cancellationToken)
   at M3u8Downloader_H.ViewModels.DownloadViewModel.<OnStart>b__41_0()
```
这种情况怎么挽救？
所在文件夹里都是碎片，打开单个文件，无法播放。怎么快速合并？

下载链接：https://live.am-hpc.com/live/qgydjpx20221218_1080p.m3u8?txSecret=97b6d8cee947061a7433efc6ff08ad07&txTime=639EF3EA

**Comment by Harlan-H** [comment]
你这地址 我访问就是403  那软件报403也没错啊 肯定网站有限制的
快速合并 看帮助文档里有->基本功能 所有方式都支持合并操作

**Comment by lweo** [comment]
> 你这地址 我访问就是403 那软件报403也没错啊 肯定网站有限制的 快速合并 看帮助文档里有->基本功能 所有方式都支持合并操作

没有找到m3u8文件，我该怎么合并呢

**Comment by lweo** [comment]
> 你这地址 我访问就是403 那软件报403也没错啊 肯定网站有限制的 快速合并 看帮助文档里有->基本功能 所有方式都支持合并操作

那是个直播，好像是直播方中途把m3u8直播换成了flv直播流。。

**Comment by lweo** [comment]
@Harlan-H 你看下我这操作对吗？为什么合并后生成的文件在另外一个磁盘，而且是0字节？

![image](https://user-images.githubusercontent.com/2786659/208840617-8f6b27ee-d9ab-4f94-a365-d816c52cf023.png)

**Comment by Harlan-H** [comment]
如果你对m3u8得结构不熟悉得话 我建议你采用xml，json，文件夹快速合并之类得方式 
我帮助文档里写了很多得方法 你都可以尝试一下  不用老在m3u8文件上较真
毕竟你让我手写m3u8文件这套结构 我都写不出来 这个其实很正常得

**Comment by lweo** [comment]
> 如果你对m3u8得结构不熟悉得话 我建议你采用xml，json，文件夹快速合并之类得方式 我帮助文档里写了很多得方法 你都可以尝试一下 不用老在m3u8文件上较真 毕竟你让我手写m3u8文件这套结构 我都写不出来 这个其实很正常得

我是用另外一个软件生成的m3u8, 但也是类似的结果，生成的ts合并文件是0字节

**Comment by Harlan-H** [comment]
你先试着弄把  我看回头过几天 更新一下 增加个类似得功能
