### ISSUE TITLE
这个录制直播怎么最长只能录制6小时的？

### ISSUE THREAD

**Issue by SUP-Eric** [Harlan-H/M3u8Downloader_H#28]

**Comment by Harlan-H** [comment]
设置中 自己选择录制时长

**Comment by SUP-Eric** [comment]
看设置里的默认时长是12小时，但是6小时就停了

**Comment by Harlan-H** [comment]
只要没有显示错误 显示的是完成 那就说明 这个链接就是完成的
那如果某个主播下播又开播 可能只有几秒的时间 那也不是这个链接了
所以 你只能在录制完成之后 上去看一下 主播是不是在播

**Comment by SUP-Eric** [comment]
多次验证是程序的问题，录制6小时就显示错误，直播是正常直播状态，没有断播

**Comment by Harlan-H** [comment]
我上次跟你说了吧 只要没有显示错误 那就是完成 
那你既然显示错误 你把错误信息给我呀

**Comment by Harlan-H** [comment]
只不过 挺佩服 这都快跨年了 还这么敬业的搞这些

**Comment by SUP-Eric** [comment]
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at M3u8Downloader_H.Common.Extensions.HttpClientExtension.GetStreamAndUriAsync(HttpClient httpClient, Uri uri, IEnumerable`1 headers, CancellationToken cancellationToken)
   at M3u8Downloader_H.M3U8.M3UFileReaderManangers.M3UFileReaderManager.GetM3u8FileInfo(Uri uri, IEnumerable`1 headers, CancellationToken cancellationToken)
   at M3u8Downloader_H.M3U8.M3UFileReaderManangers.M3UFileReaderManager.GetM3u8FileInfo(Uri uri, IEnumerable`1 headers, Boolean isRetry, CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloadLiveSource.GetLiveFileInfos(Uri url, IEnumerable`1 Headers, CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloadLiveSource.GetM3u8FileInfos(Uri url, IEnumerable`1 Headers, M3UFileInfo oldM3u8FileInfo, CancellationToken cancellationToken)
   at M3u8Downloader_H.Core.DownloaderSources.DownloadLiveSource.DownloadAsync(CancellationToken cancellationToken)
   at M3u8Downloader_H.Services.DownloadService.DownloadAsync(IDownloaderSource downloaderSource, DownloadRateSource downloadRate, CancellationToken cancellationToken)
   at M3u8Downloader_H.ViewModels.DownloadViewModel.<OnStart>b__41_0()

**Comment by SUP-Eric** [comment]
> 只不过 挺佩服 这都快跨年了 还这么敬业的搞这些

没办法，为了生活呀，冒昧啦

**Comment by Harlan-H** [comment]
这个403是网站导致的问题 
那你前面说了 到6个小时才有这个错误 那说明网站可能采用了一些技术
可能就是6个小时左右换自动换链接 
但是你网页上看直播的时候 其实是感觉不到的
因为我不知道你是通过啥技术获取到的m3u8地址 但是验证方法就是你可以在软件报错之后 在网页上再次获取m3u8地址来跟之前下载的那个m3u8地址进行比对  如果不一样 那就说明 网站采用了这个技术

**Comment by SUP-Eric** [comment]
是寇享koushare.com这个学术网站，
![微信截图_20240101201653](https://github.com/Harlan-H/M3u8Downloader_H/assets/90102015/03118da3-80b9-4762-8393-6abc769b8294)

**Comment by SUP-Eric** [comment]
https://live.am-hpc.com/live/20240101fxls_1080p.m3u8?txSecret=f5173c38963bc0af497000c4a1974a1e&txTime=6591A42F
